language: generic
sudo: required
services:
  - docker

before_instal:
  - docker build -t sangeeth472/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true sangeeth472/docker-react npm run test